### ISSUE TITLE
Too complex to integrate and not enough tutorials

### ISSUE THREAD

**Issue by motikolorado** [square/web-payments-quickstart#123]
There is too much process involved in integrating the cash app pay and the tutorial is not enough to guide a none dev. Please either use a simple API system that just require few lines of code to show the button and fetch cart price using variables or create a more elaborate tutorial for those who don't use react... just basic HTML, CSS, JS.

**Comment by maxbeatty** [comment]
Thanks for the feedback. A simple Cash App Pay implementation could look like:

```html
// where the Cash App Pay button will show
<div id="cash-app-pay"></div>

// load Web Payments SDK
<script
      type="text/javascript"
      src="https://sandbox.web.squarecdn.com/v1/square.js"
    ></script>

    <script>
      // initialize just like other payment methods
      const appId = '{APPLICATION_ID}';
      const locationId = '{LOCATION_ID}';
      const payments = window.Square.payments(appId, locationId);

      // paymentRequest represents the state of your cart
      const paymentRequest = payments.paymentRequest({
          countryCode: 'US',
          currencyCode: 'USD',
          total: {
            amount: '1.00',
            label: 'Total',
          },
        });

      // initialize the Cash App Pay payment method
      const cashAppPay = await payments.cashAppPay(paymentRequest, {
          redirectURL: window.location.href,
          referenceId: 'my-cart-or-order-id',
        });

      // handle tokenization. you'll use the token to create a payment
      cashAppPay.addEventListener(
            'ontokenization',
            async function ({ detail }) {
              const tokenResult = detail.tokenResult;
              if (tokenResult.status === 'OK') {
                // send tokenResult.token to your backend to use as source_id in the /v2/payments API
              }
            }
      );

      // show the button
      await cashAppPay.attach('#cash-app-pay');
```

Hope this helps!

**Comment by motikolorado** [comment]
How do I switch to a production environment to use my production credentials?

When I use my sandbox credentials, it works but when I use production IDs and Access token, I see invalid appID/Location ID on the browser.

**Comment by motikolorado** [comment]
Please @maxbeatty can i get the source code of the backend so i can host it on heroku with my access token.
I don't know how to send the payment token response to the backend so if you gimme a complete source for front and backend that i just need to input my credentials, it will be really appreciated.

**Comment by maorleger** [comment]
Thank you for opening this issue and allowing us to help! I hope that you have been unblocked by now but if not feel free to reach out to us via https://developer.squareup.com/forums/ and we will assist as best we can.
