### ISSUE TITLE
Getting Response object wrong after successful payment with sandbox squareup 

### ISSUE THREAD

**Issue by arvind-owl** [square/web-payments-quickstart#126]
Hi,

I am getting issue with payment response using sdk. When trying to call payment endpoint , get the wrong response after successful payment on square up end.

Request :

![req](https://user-images.githubusercontent.com/116290068/202460137-7f2c2fb8-13a6-486e-afc8-15ff97c489b6.png)

Response : 
{body: (...)
bodyUsed: false
headers: Headers {}
ok: false
redirected: false
status: 0
statusText: ""
type: "opaque"
url: ""}

Response : 
![res](https://user-images.githubusercontent.com/116290068/202460760-0bca247f-6537-4643-a0e9-cd4f19f54dfb.png)

Squareup response:

![sqrresponse](https://user-images.githubusercontent.com/116290068/202460402-752b38ee-8ccb-4ddc-9831-2cadbcd89196.png)

See Video : https://www.loom.com/share/d04ea843e92140ed99e11a7e3eb92e14

When payment successfully complete , the OK object should be true.

**Comment by maxbeatty** [comment]
the [Response.type](https://developer.mozilla.org/en-US/docs/Web/API/Response/type) is `opaque` which indicates a request to a cross-origin resource. it looks like your web page is using `localhost` and your backend is at `clindle.com` which would explain this. the simplest thing to do is to use the same host for both. more about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
