### ISSUE TITLE
Cash App Pay in Sandbox Mode is giving GENERIC_DECLINE error.

### ISSUE THREAD

**Issue by defensadev** [square/web-payments-quickstart#129]
**Describe the bug**
When using the quickstart code for cash app, providing sandbox mode + sandbox access token, is yielding the following error:

```json
{"errors": [{"code": "GENERIC_DECLINE","detail": "Authorization error: 'GENERIC_DECLINE'","category": "PAYMENT_METHOD_ERROR"}],"payment": {"id": "__ID__","created_at": "2022-12-18T20:40:08.087Z","updated_at": "2022-12-18T20:40:08.786Z","amount_money": {"amount": 100,"currency": "USD"},"status": "FAILED","delay_duration": "PT168H","source_type": "WALLET","location_id": "__LOCATION_ID__","order_id": "__ORDER_ID__","total_money": {"amount": 100,"currency": "USD"},"approved_money": {"amount": 0,"currency": "USD"},"delay_action": "CANCEL","delayed_until": "2022-12-25T20:40:08.087Z","wallet_details": {"status": "FAILED","brand": "CASH_APP","cash_app_details": {}},"application_details": {"square_product": "ECOMMERCE_API","application_id": "__SANDBOX_APP_ID__"},"version_token": "__TOKEN__"}}
```

**To Reproduce**

1. Clone the repo, go to public/examples/cash-app-pay.html
2. Add in sandbox location id + app id
3. Add .env.sandbox adding in sandbox access token
4. Verify everything is running in sandbox in server/config.js

**Expected behavior**
Success due to running in sandbox mode.

**Screenshots**
![Screen Shot 2022-12-18 at 2 45 01 PM](https://user-images.githubusercontent.com/77175338/208318515-4800d140-1d02-4cb6-8a87-0a5f95ae9285.png)

**Desktop (please complete the following information):**

- OS: Mac 11.5.2
- Browser Chrome
- Version 108.0.5359.98 (ARM)

**Additional context**
I can provide my sandbox credentials like my location id and app id if needed to help reproduce the error...

**Comment by maxbeatty** [comment]
sorry for the hiccup! the issue has been fixed and sandbox payments should be working as expected now. please let us know if you come across any other issues.

**Comment by defensadev** [comment]
Success! Thanks for the help!
