### ISSUE TITLE
Cash App Example changing price does nothing

### ISSUE THREAD

**Issue by yukosgiti** [square/web-payments-quickstart#137]
**Describe the bug**
On the Cash app example page when the price is changed from 1.00 to 10.00 or 2.00 and completing the transaction, the dashboard still says it was a 1$ transaction. (Sandbox)

**To Reproduce**
1. Edit cash-app-pay.html line 19 to 2.00.
2. Go on with the QR step.
3. Check dashboard on https://squareupsandbox.com/dashboard/sales/transactions

**Expected behavior**
Transaction should be 2 on the dashboard

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Firefox
- Version Latest

**Comment by maxbeatty** [comment]
Cash App Pay currently doesn't support the ability to change or update the options specified in a [PaymentRequest](https://developer.squareup.com/reference/sdks/web/payments/objects/PaymentRequest) object. 
https://developer.squareup.com/docs/web-payments/add-cash-app-pay#limitations-of-payment-request-updates

We’re constantly working to improve our features based on feedback like this. [Our developer forum](https://developer.squareup.com/forums/tag/web-payments-sdk) is the best place to discuss and get updates.
