### ISSUE TITLE
Is `npm i square` not same as `<script type="text" src="https://sandbox.web.squarecdn.com/v1/square.js" />`

### ISSUE THREAD

**Issue by yukosgiti** [square/web-payments-quickstart#140]
I am trying to develop a React & Next.js application with the Cash App SDK. 
When I install the library with 'npm i square' I get functions for server side processing payments etc. (Which is working great)

However, in order to use the Square API on the client side 
(e.g. generate a cash app button) it seems we cannot use the same library. 
We need to include the following script tag in our html to access `Square` namespace.
```html
<script type="text" src="https://sandbox.web.squarecdn.com/v1/square.js" />
```
For example in the examples you can do
```js
let payments = Square.payments(applicationId, locationId);
payments.cashAppPay(...)
```

However with React we can't do something like
```tsx
import Square from 'square'

function Component(props){
    const {appId, locId} = props;
    const payment = Square.payments(appId, locId) // << payments doesn't exist. 
    return <div></div>
}
```

Is there a library that gives us the namespace of the first script tag? Or Am I missing something?

**Comment by maxbeatty** [comment]
You can use [@square/web-sdk](https://www.npmjs.com/package/@square/web-sdk) (see [example](https://github.com/square/web-sdk/blob/beta/examples/tsdx/src/pay.ts)) or [react-square-web-payments-sdk](https://www.npmjs.com/package/react-square-web-payments-sdk)
