### ISSUE TITLE
Cash Pay Button In Angular

### ISSUE THREAD

**Issue by bhavinangular28** [square/web-payments-quickstart#143]
Describe the bug
Once Cash App pay button payment done and try to regenerate button again for another payment that gave previous success button details
Note:- I have product list and using angular so there is no reload scenario, is there any other way for this to make it work ?
that happen in Angular 10.0.7

To Reproduce

Open Cash App QR
Payment done
Try New Payment
See error
Screenshots
![176890284-7ccf80a6-aa92-432a-81ea-b40dd5c889be](https://user-images.githubusercontent.com/125279136/218472200-21e081b9-56fb-4141-bb40-9d940c62eba5.png)

**Comment by maorleger** [comment]
Hey @bhavinangular28  - I am happy to share that we have implemented support for restarting Cash App Pay. You will want to `destroy` the current instance and re-initialize (and attach) in order to support your scenario. Hope this helps!

**Comment by bhavinangular28** [comment]
Hello, Thank You

What should we do about that?

**Comment by bhavinangular28** [comment]
Help me to do it still not working
[image: image.png]

**Comment by maxbeatty** [comment]
Here's an example using vanilla JavaScript to create many payments using Cash App Pay on a single page

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Square Web Payments SDK - Cash App Pay - Multiple payments</title>
    <meta charset="UTF-8" />
  </head>

  <body>
    <div id="cash-app-pay"></div>

    <script src="https://sandbox.web.squarecdn.com/v1/square.js"></script>
    <script src="src/index.js"></script>
  </body>
</html>
```

```js
const appId = "YOUR_SANDBOX_APPLICATION_ID";
const locationId = "YOUR_SANDBOX_LOCATION_ID";
console.log("initializing payments...");
const payments = window.Square.payments(appId, locationId);

async function initializeCashAppPay(paymentCount) {
  console.log("initializing Cash App Pay...");
  const paymentRequest = payments.paymentRequest({
    countryCode: "US",
    currencyCode: "USD",
    total: {
      amount: `${paymentCount}.00`,
      label: "Total"
    }
  });
  const cashAppPay = await payments.cashAppPay(paymentRequest, {
    redirectURL: window.location.href,
    referenceId: "my-website-00000001"
  });

  cashAppPay.addEventListener("ontokenization", async function (event) {
    console.log("ontokenization", event);
    // TODO: use event.detail.tokenResult to create a payment

    setTimeout(async () => {
      await cashAppPay.destroy();
      console.log("let's create another payment!");
      initializeCashAppPay(++paymentCount);
    }, 5000);
  });

  console.log("attaching Cash App Pay...");
  await cashAppPay.attach("#cash-app-pay");
}

initializeCashAppPay(1);
```

See it in action: https://codesandbox.io/s/determined-violet-gx2kcl?file=/src/index.js

If you have any other issues, [our Developer Forums](https://developer.squareup.com/forums/tag/web-payments-sdk) is a great place to get help.

**Comment by bhavinangular28** [comment]
Awesome, thanks!

**Comment by bhavinangular28** [comment]
I have implemented the model for one, but the second time when the model is opened, it doesn't regenerate.
![Screenshot_1](https://user-images.githubusercontent.com/125279136/234567652-3c977443-b00d-4133-99f0-e3dd3092d17b.png)
