### ISSUE TITLE
Local dev server runs and shows index.html page BUT deployed to Heroku  keeps returning 503 when opening app

### ISSUE THREAD

**Issue by medatxdistro** [square/web-payments-quickstart#186]
I need to host a simple credit card payment processing page on heroku. I followed the instructions on the readme and I can get my local dev server to show the index.html page. 

However, when I deploy this repo to heroku and open the app, I only get 503's.

Any leads, or a better place to get help with this would be greatly appreciated!

Blue Skies,
Michael

**Comment by maxbeatty** [comment]
It's encouraging that this is running locally for you. You may want to investigate your Heroku logs further. There might be a configuration issue or some other problem beyond what we're able to help support here.
