### ISSUE TITLE
Square Payment ACH one Time Token Error 

### ISSUE THREAD

**Issue by SaqibSajjad** [square/web-payments-quickstart#204]
Hi I'm trying To get One Time Token for ACH and that token Would to send backend for futhur Processing But I'm facing issue when I pass account Holder Name  dynamically my application crash & if I pass static or empty string to accountHolderName in ach.tokenize () method here is my code :
SquarePayment = {
Load : function ( ) {

var payments = Square.payments('MY-APPLICATION_ID', 'MY-LOCATION_ID');
payments.ach({ redirectURI: window.location.href, transactionId: 'my-distinct-transaction-id' }).then(function (ach) {
            $('#ach-submit').on('click', function () {
                debugger;
                const paymentForm = $('#payment-form-ach');
                const formData = new FormData(paymentForm[0]);
                const patientName = `${formData.get('givenName')} ${formData.get('familyName')}`;
                
                try {
                    ach.tokenize({ "accountHolderName": patientName } );

                } catch (e) {
                    console.log(error);
                }
            });
            ach.addEventListener('ontokenization', function (tokenResult) {
                if (tokenResult.detail.tokenResult.status == 'OK') {
                    console.log(`Payment token is ${tokenResult.detail.tokenResult.token}`);
                    data.paymentToken = tokenResult.detail.tokenResult.token;

                } else {
                    console.error(tokenResult.error);
                }
            });
        }).catch(function (error) {
            console.log(error);
        });
    },
}

**Comment by maxbeatty** [comment]
We believe this may have been caused by an account holder name that only contained whitespace. We've released a fix to handle this better. Please reopen if you're still experiencing this issue.
