### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by talha2k** [square/web-payments-quickstart#240]
Is there any PHP version available for this web payments with example.

**Comment by maxbeatty** [comment]
This quickstart uses [Square's Node.js SDK](https://developer.squareup.com/docs/sdks/nodejs) in a simple server to create payments:

https://github.com/square/web-payments-quickstart/blob/042c73641a18f2b80a8d09d3cd09f5ad61871082/package.json#L40

https://github.com/square/web-payments-quickstart/blob/042c73641a18f2b80a8d09d3cd09f5ad61871082/server/square.js#L5-L8

https://github.com/square/web-payments-quickstart/blob/042c73641a18f2b80a8d09d3cd09f5ad61871082/server.js#L63

You can use [Square's PHP SDK](https://developer.squareup.com/docs/sdks/php) to [create a simple server](https://developer.squareup.com/docs/sdks/php/quick-start) with a [`/payment` endpoint](https://github.com/square/web-payments-quickstart/blob/042c73641a18f2b80a8d09d3cd09f5ad61871082/public/examples/card-payment.html#L28) for the examples to use.

Our [forums](https://developer.squareup.com/forums/) and [Discord community](https://discord.gg/squaredev) are a great place for more help getting this wired up.
