### ISSUE TITLE
React integration example

### ISSUE THREAD

**Issue by marc-aurele-besner** [square/web-payments-quickstart#40]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to integrate this example to a react/typescript project, 

**Describe the solution you'd like**
A simple example of square integrated on a react website.

**Describe alternatives you've considered**
Most of all examples/documentation referring to react + square refer to depreciated tools. 

**Additional context**
I try to integrate this current repo to a react/typescript project, I got rid of all errors, but the input and button for card payment do not work yet. I'll play with it a bit more.

**Comment by premachb** [comment]
Hi @marc-aurele-besner

There is a React Wrapper here https://github.com/weareseeed/react-square-web-payments-sdk that Square recommends for developers looking for a React Wrapper of the Web Payments SDK. Hope that helps

**Comment by marc-aurele-besner** [comment]
Hi @premachb 

Thank you very much for your help :)
